### ISSUE TITLE
Cannot find module 'picocolors'

### ISSUE THREAD

**Issue by klren0312** [UrielCh/adbkit#4]
### problem

test code

```js
const Adb = require('@u4/adbkit')

const client = Adb.createClient()

(async () => {
  const device = await client.listDevice()
  console.log(device)
})()
```

throw error
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'picocolors'
Require stack:
- D:\vueProject\testP\node_modules\@u4\adbkit\dist\adb\command\host-transport\ipRoute.js
- D:\vueProject\testP\node_modules\@u4\adbkit\dist\adb\command\host-transport\index.js
- D:\vueProject\testP\node_modules\@u4\adbkit\dist\adb\DeviceClient.js
- D:\vueProject\testP\node_modules\@u4\adbkit\dist\adb\command\host\devices.js
- D:\vueProject\testP\node_modules\@u4\adbkit\dist\adb\command\host\index.js
- D:\vueProject\testP\node_modules\@u4\adbkit\dist\adb\client.js
- D:\vueProject\testP\node_modules\@u4\adbkit\dist\adb.js
- D:\vueProject\testP\node_modules\@u4\adbkit\dist\index.js
- D:\vueProject\testP\adb.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (D:\vueProject\testP\node_modules\@u4\adbkit\dist\adb\command\host-transport\ipRoute.js:8:38)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
```

### analysis
move the `picocolors` to `dependencies` ?
![1650015274(1)](https://user-images.githubusercontent.com/10903843/163554929-1c3ad670-f9a8-49a0-914d-c82e3b2b1450.png)

**Comment by UrielCh** [comment]
oups....

colors just dropped

install picocolors, for now, until the next release.

**Comment by UrielCh** [comment]
[v3.1.15](https://github.com/UrielCh/adbkit/releases/tag/v3.1.15) is out.

**Comment by klren0312** [comment]
> [v3.1.15](https://github.com/UrielCh/adbkit/releases/tag/v3.1.15) is out.

Thank you, because of you, warm the four seasons
